language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack: 79bits:PbBFZ49YbmKTBlmwVnylv79D

branches:
  only:
    - master

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 WP_TRAVISCI=grunt TRAVIS_NODE_VERSION="6"


install:
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - npm install

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer install
    - npm install -g npm
    - npm install -g grunt-cli
    - npm install
    - npm prune
    - phpenv versions
    - npm --version
    - node --version

script:
    - phpunit
    - grunt default
